site_name: CEL EPLAN user Manual
theme:
  name: material

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects: project/cel-epl-pro-001.md


  - Schneider:
      - ACB: schneider/cel-sch-acb-001.md
